(function(g){var window=this;'use strict';var C3=function(a){a.publish("cardstatechange",a.Vk()&&a.Dp()?1:0)},D3=function(a,b){var c=g.cb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},dqb=function(a){var b=g.Rs(a);
a=g.Us(a);return new g.Fs(b.x,b.y,a.width,a.height)},eqb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.rB(a,b,function(){g.sB(e);c.apply(a,arguments)},d)},G3=function(a){a=g.fb(a);
delete E3[a];g.gd(E3)&&F3&&F3.stop()},gqb=function(){F3||(F3=new g.Gv(function(){fqb()},20));
var a=F3;a.isActive()||a.start()},fqb=function(){var a=g.lb();
g.Uc(E3,function(b){hqb(b,a)});
g.gd(E3)||gqb()},H3=function(a,b,c,d){g.Sv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},hqb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;iqb(a,a.progress);a.progress==1?(a.j=0,G3(a),a.onFinish(),a.Zr()):a.isPlaying()&&a.ZM()},iqb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},jqb=function(a,b){g.Ab.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},I3=function(a,b,c,d,e){H3.call(this,b,c,d,e);
this.element=a},kqb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
I3.call(this,a,b,c,d,e)},lqb=function(a){return Math.pow(a,3)},mqb=function(a){return 3*a*a-2*a*a*a},nqb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},J3=function(a){return a.baseUrl||null},K3=function(a,b){return g.Ot(g.$r(a,b),function(c){return!!c})},oqb=function(a,b,c){function d(pa){var ia=pa.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var ta=f(ia.unsubscribedButtonText),aa=f(ia.subscribedButtonText);if(ia.subscribed){var T=f(ia.subscriberCountWithUnsubscribeText);var Ha=f(ia.subscriberCountText)}else T=f(ia.subscriberCountText),Ha=f(ia.subscriberCountWithSubscribeText);var x=null;if(pa.signinEndpoint){x=D3(pa,"signinEndpoint","webNavigationEndpointData","url");if(!x){var ba,Ma;x=(Ma=g.V((ba=ia.signInEndpoint)==null?void 0:ba.commandMetadata,g.v2))==null?void 0:
Ma.url}if(!x)return null}return ta&&(aa||x)?{subscribed:ia.subscribed,subscribeText:ta,subscribeCount:T,unsubscribeText:aa,unsubscribeCount:Ha,enabled:ia.enabled,signinUrl:x,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ia=[],ta=pa.videoId;ta&&ia.push("v="+ta);(ta=pa.playlistId)&&ia.push("list="+ta);(pa=pa.startTimeSeconds)&&ia.push("t="+pa);return"/watch?"+ia.join("&")}}
function f(pa){if(!pa)return null;var ia=pa.simpleText;return ia?ia:pa.runs?g.$r(pa.runs,function(ta){return ta.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,w=!1,A=null,C=null,F=null,H=null,L=null,M=null;if(h==="VIDEO")g.V(l,g.gF)?m=g.V(l,g.gF).url:(M=g.V(l,g.GS),m=e(M)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.V(l,g.gF)?m=g.V(l,g.gF).url:(M=g.V(l,g.GS),m=e(M)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(w=D3(l,"browseEndpoint","browseId"))u=w,m="/channel/"+u;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=D3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=D3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=D3(b,"title","accessibility","accessibilityData","label");var P=b.endpoint?b.endpoint.clickTrackingParams:
null,fa="";if(b.metadata){var ka=f(b.metadata);ka&&(fa=ka)}return{id:"element-"+c,type:h,title:f(b.title),metadata:fa,callToAction:f(b.callToAction),GX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,uF:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,b$:n,sessionData:P?{itct:P}:null,tea:q,PD:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:K3(b.impressionUrls||[],J3),Q9:K3(b.hovercardShowUrls||[],J3),clickUrls:K3(l.loggingUrls||[],J3),visualElement:g.kE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:M||null}},pqb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:K3(a.impressionUrls||[],J3),elements:K3(a.elements||[],function(d,e){return oqb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.kE(a.trackingParams));return c},qqb=function(a){g.kV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.wR(a)||g.yR(a);this.events=new g.NJ(this);g.N(this,this.events);this.events.T(this.player,g.TI("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.UI("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.kc);this.events.T(window,"focus",this.Cca);this.load();var b=g.yf("STYLE");(g.nf("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Hf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},rqb=function(a){return a.player.getVideoData().Kf?"current":a.Z?"new":"current"},L3=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},sqb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=pqb(f,rqb(a))));M3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Wv;d&&(c.postParams={ad_tracking:d});if(b=g.IXa(b))if(b=g.je(b),b=g.de(b))a.C=g.KA(b,c)},M3=function(a,b,c){c=c===void 0?!0:c;
a.player.sf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&tqb(a);c=[];d=new g.SI(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.LT(a.player,a.B.element,4),a.D=new g.uF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=uqb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.LT(a.player,f.element,4);var h=new g.SI(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);vqb(a,f,e)}else g.qE(new g.MB("buildEndscreenElement null",
e))}a.player.jf(c);a.kc()}},tqb=function(a){var b=g.lE(),c=g.mE();
c&&b&&a.endscreen.visualElement&&g.qA(g.zE)(void 0,c,b,a.endscreen.visualElement)},uqb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.PD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:N3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:O3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Vv(b.title||"")},va:b.title},{I:"div",S:b.uF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.PD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",X:N3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",X:{href:O3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Vv(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.PD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],X:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Vv(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:N3(b)}]};c=new g.W(c);var d=g.of(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Nv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.UV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.PD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",X:{dir:g.Vv(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],X:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:N3(b)},{I:"div",S:"ytp-ce-expanding-icon",X:wqb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.PD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",X:{dir:g.Vv(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:O3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",X:N3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Nv(c.element,"ytp-ce-placeholder");return c},N3=function(a){if(a.GX)var b=a.GX.thumbnails;
return wqb(b?b[b.length-1].url:null)},wqb=function(a){return a?{style:"background-image: url("+a+")"}:{}},vqb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Nv(b.element,"ytp-ce-force-expand"),P3(a,c.id,!0)):(g.Pv(b.element,"ytp-ce-force-expand"),g.Pv(b.element,"ytp-ce-element-hover"),P3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){xqb(a,b,c)});
b.listen("mouseleave",function(){yqb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Nv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){zqb(a,c,m)});
b.listen("keypress",function(m){zqb(a,c,m)});
b.listen("focus",function(){xqb(a,b,c)});
b.listen("blur",function(){yqb(a,b,c)});
b.listen("touchstart",function(){xqb(a,b,c)});
var l=g.tf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Pv(b.element,"ytp-ce-element-hover");g.Pv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.tf("ytp-sb-subscribe",b.element));d(g.tf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},zqb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.Mv(d,"ytp-ce-element");){g.Mv(d,"subscribe-label")&&Aqb(a,b);
if(g.Mv(d,"ytp-ce-channel-subscribe"))return;d=g.If(d)}if(!d||g.Mv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])yqb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.tea==="new")Aqb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(O3(a,b.targetUrl)),c=g.de(c),g.WF(c,void 0,b.sessionData);else{var e=g.HR(a.player.U())||a.player.getVideoData().Kf,f=function(){var h=O3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.vA(h);e&&n&&
(n.v||n.list)?a.player.ip(n.v,l,n.list,!1,void 0,m||void 0):g.kza(h,l)};
Aqb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},O3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.OR(a)+b}else return"";return b},xqb=function(a,b,c){g.Mv(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Nv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Gv(function(){g.Nv(b.element,"ytp-ce-element-hover")},200)).start():g.Nv(b.element,"ytp-ce-element-hover"),Q3(a,c.Q9),P3(a,c.id,!0))},yqb=function(a,b,c){g.Pv(b.element,"ytp-ce-element-hover");
g.Pv(b.element,"ytp-ce-force-expand");P3(a,c.id,!1)},P3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Rv(a.j[e].element,"ytp-ce-element-shadow-show",c)},Q3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||L3(a))c&&c();else{b=Bqb(a,b);var e=0,f=!1,h=new g.Gv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.fD(b[a],d)}},Aqb=function(a,b,c){Q3(a,b.clickUrls,c);
(a=g.mE())&&b.b$&&g.GE(a,b.visualElement)},Bqb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Cqb(b[d],c));return a},Cqb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Dqb=function(a){return typeof a==="string"?a:""},R3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Eqb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},S3=function(a){return a.value?a.value:null},T3=function(a){if(!a)return null;
var b=g.je(Dqb(a.value));b=g.de(b);if(!b)return null;var c=R3(a.target,Fqb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new Eqb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},Gqb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Jqb=function(a){if(!a)return null;
var b=R3(a.type,Hqb),c=R3(a.trigger,Iqb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=T3(a?a:null);return b?new Gqb(b,c,a):null},Kqb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Lqb=function(a,b){return g.Db(a.action,b)},Mqb=function(a,b){this.context=a;
this.j=b},Nqb=function(a){return a.customMessage?U3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",X:{style:a},V:c}},Oqb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(U3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},U3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Vv(c);return{I:a,X:b,va:c}},Pqb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.bE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.bE+");");c.dir=g.Vv(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,X:c,V:d}},W3=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.jj.click,5)}},Qqb=function(a,b){this.merchant=a;
this.price=b},Rqb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},Sqb=function(a,b){return b?b:Rqb(a)?"current":"new"},X3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Wa=new Map;this.eb=new Map;this.context.J.addEventListener(g.TI("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.UI("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.aN(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},Tqb=function(a){var b;
return((b=g.V(a,g.gF))==null?0:b.url)?g.V(a,g.gF).url:(a=g.V(a,g.GS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Z3=function(a,b,c){return{fZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
l2:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Uqb=function(a,b,c){X3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.Na=this.Kb=this.C=this.isInitialized=!1;this.cards=[];this.Fb=this.Z=this.Ma=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Hf=this.Ha=null;this.K=0;this.Fa=new g.Gv(function(){},c.W.Pl?4E3:3E3);
g.N(this,this.Fa);this.gb=new g.Gv(function(){});
g.N(this,this.gb);this.Ca=new Mqb(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",X:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",X:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.N(this,this.Y);this.D=this.Y.element;this.Za=new g.uF(this.Y,330);g.N(this,this.Za);this.Jb=g.tf("iv-drawer-header-text",this.D);this.B=g.tf("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Kb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Kb=d.C)&&a4(d)});
this.Sa=new g.NJ(this);g.N(this,this.Sa);this.J.addEventListener("videodatachange",this.Ut.bind(this))},Vqb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Kf(a.Jb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ha=g.kE(b.trackingParams);a.N=g.kE(b.closeTrackingParams);a.Hf=g.kE(b.iconTrackingParams)},Wqb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.UE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,jj:{},Gp:null,Pj:e.trackingParams?g.kE(e.trackingParams):null,Hf:f&&f.trackingParams?g.kE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
bE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};b4(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.UE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:c4(a,c,b,f),sponsored:!1,jj:Z3(f,e,f.command),Gp:f.trackingParams?g.kE(f.trackingParams):null,Pj:e.trackingParams?g.kE(e.trackingParams):null,Hf:l&&l.trackingParams?g.kE(l.trackingParams):null,imageUrl:d4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.UE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,bE:null,title:f.title?g.UE(f.title):"",customMessage:f.callToAction?g.UE(f.callToAction):"",url:g.V(f.command,g.gF).url?T3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.gF).url}):null,onClickCommand:null};b4(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.UE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,e),sponsored:!1,jj:Z3(e,f,e.endpoint),Gp:e.trackingParams?g.kE(e.trackingParams):null,Pj:f.trackingParams?g.kE(f.trackingParams):null,Hf:l&&l.trackingParams?g.kE(l.trackingParams):null,channelId:g.V(e.endpoint,g.VS).browseId,customMessage:e.customText?g.UE(e.customText):null,profileImageUrl:d4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.UE(e.channelName):"",metaInfo:[e.subscriberCountText?g.UE(e.subscriberCountText):""],url:T3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.VS).canonicalBaseUrl?g.V(e.endpoint,g.VS).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.VS).browseId}),onClickCommand:null};b4(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.UE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,e),sponsored:!1,jj:Z3(e,f,e.action),Gp:e.trackingParams?g.kE(e.trackingParams):null,Pj:f.trackingParams?g.kE(f.trackingParams):null,Hf:l&&l.trackingParams?g.kE(l.trackingParams):null,EH:d4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.UE(e.customMessage):null,playlistVideoCount:g.UE(e.playlistVideoCount),title:e.playlistTitle?g.UE(e.playlistTitle):"",metaInfo:[e.channelName?g.UE(e.channelName):
"",e.videoCountText?g.UE(e.videoCountText):""],url:T3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Tqb(e.action)}),onClickCommand:null};b4(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.UE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,e),sponsored:!1,jj:Z3(e,f,e.action),Gp:e.trackingParams?g.kE(e.trackingParams):null,Pj:f.trackingParams?g.kE(f.trackingParams):null,Hf:l&&l.trackingParams?g.kE(l.trackingParams):null,EH:d4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.UE(e.lengthString):null,customMessage:e.customMessage?g.UE(e.customMessage):null,title:e.videoTitle?g.UE(e.videoTitle):"",metaInfo:[e.channelName?g.UE(e.channelName):
"",e.viewCountText?g.UE(e.viewCountText):""],isLiveNow:!!e.badge,url:T3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Tqb(e.action)}),onClickCommand:null};b4(a,b)}}}}}a.K++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Yqb=function(a,b){if(b=Xqb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Bf.id),g.Hf(b.qO),g.Hb(a.cards,b),a.II(),e4(a)},$3=function(a,b,c){if(!a.C){a.Za.show();
a.Va=new g.Gv(function(){g.Nv(a.context.J.getRootNode(),g.xY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.mE();d&&a.Ha&&a.N&&g.EE(d,[a.Ha,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.YZ||(f.YZ=!0,Zqb(a.context.logger,f.Bf.jj.fZ,b)),d&&g.EE(d,[f.Bf.Gp]);C3(a.J);c&&(a.G=new g.Gv(function(){a.Ma=a.Z;a.Fb.focus()},330),a.G.start())}},a4=function(a){a.C&&(a.Za.hide(),g.xB(a.Sa),g.Pv(a.context.J.getRootNode(),g.xY.IV_DRAWER_OPEN),a.C=!1,C3(a.J),a.G&&a.G.stop(),a.G=new g.Gv(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},$qb=function(a){g.Ov(a.Ib(),
[g.xY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.LT(a.J,a.D,5);a.RD();a.Z=g.tf("ytp-cards-button",a.J.getRootNode());a.Fb=g.tf("iv-drawer-close-button",a.D);a.isInitialized=!0},arb=function(a){a.qa.push(g.tD("iv-teaser-shown",a.P4,a));
a.qa.push(g.tD("iv-teaser-hidden",a.v$,a));a.qa.push(g.tD("iv-teaser-clicked",a.O4,a));a.Ab=!0},brb=function(a,b){var c;
return b.onClickCommand&&((c=g.V(b.onClickCommand,g.Fmb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},crb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.fWa(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.V(h[0],g.F3a))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},b4=function(a,b){if(!brb(a,b)||crb(a,b)){var c=drb(a,b);
if(c){var d={Bf:b,qO:c.element,YZ:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||arb(a),Yqb(a,b.id),c=a.findLastIndex(d),g.Ob(a.cards,c,0,d));else{a.isInitialized||$qb(a);Yqb(a,b.id);var e=a.findLastIndex(d);g.Ob(a.cards,e,0,d);c.Ja(a.B,e);a.II()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,e4(a),erb(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&frb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){frb(a,d)}),e4(a))}}},drb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=Pqb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",X:{href:b.url?S3(b.url)||"":""},V:[V3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[U3("h2",void 0,b.title),d]}]}]};c=new g.W(c);W3(a,g.pf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],X:{href:S3(b.url)||"","data-ytid":b.channelId},V:[V3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[Nqb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},Oqb(b)]}]}]};c=new g.W(c);W3(a,g.pf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",X:{href:S3(b.url)||""},V:[V3(b.EH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[Nqb(b),U3("h2","iv-card-primary-link",b.title),Oqb(b)]}]}]};
c=new g.W(c);W3(a,g.pf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=b.offers.length!=0;c=["iv-card"];d="";var f=Pqb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?S3(b.url)||"":"";c={I:"div",Ka:c,X:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",X:{href:e},V:[U3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.yf("span");g.Kf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Ed(d,"adInfo");W3(a,g.pf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",X:{href:((c=b.url)==null?void 0:S3(c))||""},V:[V3(b.EH,d),{I:"div",S:"iv-card-content",V:[Nqb(b),U3("h2","iv-card-primary-link",b.title),Oqb(b),f]}]}]};c=new g.W(e);W3(a,g.pf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},grb=function(a){if(a.j)return a.j.Bf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.as(a.cards,function(c){return c.Bf.type==="productListing"})}return g.as(a.cards,function(c){return c.Bf.type==="productListing"})},e4=function(a){g.Rv(a.J.getRootNode(),"ytp-cards-shopping-active",grb(a))},frb=function(a,b){if(!g.Mv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.mE(),d=a.j?a.j.Bf.Hf:a.Hf;
c&&d&&g.FE(c,[d]);a.j=b;e4(a)}(c=a.isInitialized&&a.Ib().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Bf.teaserDurationMs&&a.J.dC(!0,{teaserText:b.Bf.teaserText,durationMs:b.Bf.teaserDurationMs,onClickCommand:b.Bf.onClickCommand});a.gb.isActive()||((!a.C||!a.Fa.isActive()&&a.Na)&&erb(a,b),a.gb.start(910+b.Bf.teaserDurationMs))}},erb=function(a,b){a.Y.Hb?(b=new H3([0,
a.B.scrollTop],[0,b.qO.offsetTop],600,mqb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.QE(a.Y,!0),a.B.scrollTop=b.qO.offsetTop,g.QE(a.Y,!1))},f4=function(a){return a.j&&a.j.Bf?a.j.Bf:a.cards[0]&&a.cards[0].Bf?a.cards[0].Bf:null},Xqb=function(a,b){return g.Db(a.cards,function(c){return c.Bf.id===b})},g4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},hrb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},h4=function(a,b,c){g4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},irb=function(a,b){var c=c===void 0?0:c;
var d=dqb(b).width;g.Ps(b,d);c=new kqb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,lqb);g.N(a,c);a.context.C.listen(c,"begin",function(){g.Vs(b,!0)});
c.play()},lrb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.UV(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Vs(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Is(l,"right",b.image_width+"px");g.Bf(a.Ib(),l);a.C=new g.Gv(function(){jrb(a,h,l)},500);
g.N(a,a.C);a.context.j.listen(a.Ib(),"mouseover",function(){krb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Ib(),"mouseout",function(){a.C.start()})}},krb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Us(b);a.j||(b.style.width=g.Os(f.width,!0),c.style.width=g.Os(f.width,!0));g.Is(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Is(d,"right","1px");a.D=!0;g.Vs(b,!0);a.G=new g.Gv(function(){g.Nv(this.Ib(),"iv-branding-active")},0,a);
a.G.start()}},jrb=function(a,b,c){g.Pv(a.Ib(),"iv-branding-active");
a.K=new g.Gv(function(){g.Vs(b,!1);a.j||(c.style.width=g.Os(0,!0))},250);
a.K.start();a.D=!1},mrb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.W=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},nrb=function(a,b,c){g4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.Gv(function(){d.j.setAttribute("aria-hidden","true");g.Vs(d.C,!1);g.Vs(d.B,!0)},700,this);
g.N(this,this.G)},qrb=function(a,b,c){c.stopPropagation();
orb(a);prb(a,b);a.j.focus()},rrb=function(a){a.isCollapsed||a.Z||a.D||(g.Nv(a.Ib(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},orb=function(a){a.G.stop();
a.isCollapsed&&(g.Qv(a.Ib(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Vs(a.B,!1),g.Vs(a.C,!0))},prb=function(a,b){a.D||(a.D=g.og(function(){srb(this);
rrb(this)},b,a))},srb=function(a){a.D&&(g.Ta.clearTimeout(a.D),a.D=null)},trb=function(a){this.J=a},Zqb=function(a,b,c){b&&(c?i4(a,b.map(function(d){return g.cv(d,c)})):i4(a,b))},i4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.fD(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},urb=function(a){g.kV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new trb(this.player);this.D=new g.NJ(this);this.G=this.N=null;this.events=new g.NJ(this);this.Zg=this.Y=this.j=null;this.ra=[];g.N(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.Q4,this);this.subscribe("resize",this.kL,this);this.player.U().Na.subscribe("vast_info_card_add",this.j0,this);g.N(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.B);g.LT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.N(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.Xu()&&this.load();var c=this.createElement({I:"style"});(g.nf("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Hf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},vrb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Vs(a,!1);return a},wrb=function(a,b){b=!b.isCued()&&!g.BF(b,1024);
g.QE(a.B,b);g.QE(a.C,b)},xrb=function(a,b,c){a.Z=!0;
a.G=g.KA(b,c)},yrb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(yrb(a,e))}return c},Crb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.DA(h)&&h.responseXML?h.responseXML:null)&&zrb(a,h)}};
g.UB()&&(d.onFinish=Arb(a,d.onFinish));d.postParams={ic_only:"1"};Brb(d,c);a.Z=!0;g.KA(b.Va,d)}}},Brb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.NI&&(a.postParams.ic_coll=b.NI);b.rO&&(a.postParams.ic_xml=b.rO);b.zM&&(a.postParams.ic_track=b.zM)},Drb=function(a){var b=new g.W({I:"div"});
g.Vs(b.element,!1);var c=new Uqb(a.player,b.element,j4(a));g.N(c,b);b.Ja(a.B.element);c.oH();return c},Frb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,Erb(a,b),b.headerText&&a.Zg&&(c=g.UE(b.headerText),a.Zg.setAttribute("title",c))},j4=function(a){if(!a.Y){var b=new nqb(a);
g.N(a,b);var c=new g.oq(a);g.N(a,c);a.Y=new mrb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.zj)}return a.Y},zrb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.mE();if(e){var f=g.lE();f&&g.qA(g.Jxa)(void 0,e,f,[g.kE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=yrb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=R3(f.type,Grb),p=R3(f.style,Hrb),q=Dqb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=Jqb;if(t==null)var u=null;else if(g.cb(t)){l=[];for(var w=g.v(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new Kqb(m,n,p,u,r):null}else e=null}catch(ka){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=vrb(f),L=null;switch(l.type){case "branding":if(f.player.U().Fd)break;f.B.element.appendChild(H);L=new h4(H,j4(f),l);break;case "promotion":g.LT(f.player,H,4),L=new nrb(H,j4(f),l)}L&&L.oH();if(f=L)g.N(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=Drb(a),g.N(a,a.j));if(e.type==="card"){H=a.j;var M=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(M)switch(f=e.tracking||{},f={fZ:f.impression,click:f.click,close:f.close,l2:f.teaser_impression,uM:f.teaser_click},l=e.tracking_params||{},L=null,M){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.kE(l.card):null,Pj:l.teaser?g.kE(l.teaser):null,Hf:l.icon?g.kE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:T3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,
Gp:l.card?g.kE(l.card):null,Pj:l.teaser?g.kE(l.teaser):null,Hf:l.icon?g.kE(l.icon):null,EH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:T3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b4(H,c);break;case "productListing":e.signin_url&&(L=T3({target:"current",value:e.signin_url}));M=[];for(var P=e.offers||[],fa=0;fa<P.length;fa++)M.push(new Qqb(g.bf(P[fa].merchant),
g.bf(P[fa].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.kE(l.card):null,Pj:l.teaser?g.kE(l.teaser):null,Hf:l.icon?g.kE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,bE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:T3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),Qrb:L,Prb:e.signin_title?e.signin_title:void 0,Orb:e.signin_message?e.signin_message:void 0,offers:M,onClickCommand:null};b4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.kE(l.card):
null,Pj:l.teaser?g.kE(l.teaser):null,Hf:l.icon?g.kE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,bE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:T3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};b4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.kE(l.card):null,Pj:l.teaser?g.kE(l.teaser):null,Hf:l.icon?g.kE(l.icon):null,EH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:T3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},b4(H,c)}}else Vqb(a.j,e);c=!0}}c&&
(C3(a.player),a.kL())},Erb=function(a,b){var c=!1;
a.j||(a.j=Drb(a),g.N(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Wqb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.bT(f)||(c=a.j,d=b.headerText?g.UE(b.headerText):"",g.Kf(c.Jb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ha=b.trackingParams?g.kE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.kE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Hf=b.icon.infoCardIconRenderer.trackingParams?g.kE(b.icon.infoCardIconRenderer.trackingParams):null,a.kL());C3(a.player)}},Irb=function(a,b,c,d,e){if(!a.player.U().Fd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.VS)&&g.V(b.navigationEndpoint,g.VS).browseId&&f.push(new Gqb("openUrl","click",new Eqb("/channel/"+g.V(b.navigationEndpoint,g.VS).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.WS)){d.channel_id=g.V(b.subscribeButton,g.WS).channelId;var l;b=g.V(b.subscribeButton,g.WS);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.UE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.UE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.UE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.UE(b.subscriberCountWithSubscribeText)));var m,n=((m=g.V((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.v2))==null?void 0:m.url)||"";l={subscribeText:g.UE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.UE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Kqb(c,"branding","branding",f,d);l=vrb(a);a.B.element.appendChild(l);f=new h4(l,j4(a),f);f.oH();g.N(f,f);a.K[c]=f}},Arb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.La()||a.ra.push(g.Cv.Qi(function(){b.apply(null,g.qa(c))}))}},Jrb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.ET.prototype.dC=g.ea(28,function(a,b){var c=g.CV(this.zb());c&&c.dC(a,b)});
var E3={},F3=null;g.nb(H3,g.Sv);g.k=H3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;G3(this);this.startTime=a=g.lb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.cL();this.Ln("play");this.isPaused()&&this.Ln("resume");this.j=1;var b=g.fb(this);b in E3||(E3[b]=this);gqb();hqb(this,a);return!0};
g.k.stop=function(a){G3(this);this.j=0;a&&(this.progress=1);iqb(this,this.progress);this.onStop();this.Zr()};
g.k.pause=function(){this.isPlaying()&&(G3(this),this.j=-1,this.Ln("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.Ln("destroy");H3.Qf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.ZM=function(){this.Ln("animate")};
g.k.Ln=function(a){this.dispatchEvent(new jqb(a,this))};
g.nb(jqb,g.Ab);g.nb(I3,H3);I3.prototype.C=function(){};
I3.prototype.ZM=function(){this.C();I3.Qf.ZM.call(this)};
I3.prototype.Zr=function(){this.C();I3.Qf.Zr.call(this)};
I3.prototype.cL=function(){this.C();I3.Qf.cL.call(this)};
g.nb(kqb,I3);kqb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.y(nqb,g.I);g.k=nqb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=g.rB(a,b,c);this.j.push(a);return a};
g.k.OF=function(a,b,c,d){c=(0,g.gb)(c,d||this.B);a=eqb(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.sB(a);g.Hb(this.j,a)};
g.k.removeAll=function(){g.sB(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.I.prototype.xa.call(this)};g.y(qqb,g.kV);g.k=qqb.prototype;g.k.load=function(){g.kV.prototype.load.call(this);if(!L3(this)){var a=g.JXa(this.player.getVideoData());a?(a=pqb(a,rqb(this)),M3(this,a,!1)):sqb(this)}};
g.k.unload=function(){M3(this,null);this.C&&(this.C.abort(),this.C=null);g.kV.prototype.unload.call(this)};
g.k.Th=function(a,b){return L3(this)?a==="loadCustomEndscreenRenderer"?(a=pqb(b,"new"),M3(this,a),!0):null:null};
g.k.getOptions=function(){return L3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Krb.length;f++){var h=Math.abs(b.width-Krb[f]);if(e===-1||d>=h)e=f,d=h}d=Lrb[e];this.B&&g.Is(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ts(e.element,m,f);g.Ps(e.element,n,p);g.Qv(e.element,Mrb);m>256||f>256?g.Nv(e.element,"ytp-ce-large-round"):m>96||f>96?g.Nv(e.element,"ytp-ce-medium-round"):g.Nv(e.element,"ytp-ce-small-round");g.Qv(e.element,Nrb);m=h.left+h.width/2;h=h.top+l/2;g.Nv(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Qv(e.element,Lrb);g.Nv(e.element,d);(e=g.of(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Is(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")Q3(this,this.endscreen.impressionUrls),(a=g.mE())&&this.endscreen.visualElement&&g.DE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Nv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Nv(b,"ytp-ce-shown");Q3(this,c.impressionUrls);(b=g.mE())&&g.DE(b,c.visualElement);this.player.U().N&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Pv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Pv(b,"ytp-ce-shown");this.player.U().N&&this.player.ib("endscreenelementhidden",a)}};
g.k.Cca=function(a){var b=this;a.target===window&&(new g.Gv(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Qv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Krb=[346,426,470,506,570,640,853,1280,1920],Lrb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Nrb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Mrb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Fqb={ywa:"current",OXa:"new"};var Hqb={CLOSE:"close",F0a:"openUrl",SUBSCRIBE:"subscribe"},Iqb={Jua:"click",CLOSE:"close",GIa:"hidden",O6a:"rollOut",P6a:"rollOver",J8a:"shown"};Kqb.prototype.Ke=function(){var a=Lqb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var Hrb={Xoa:"anchored",H3:"branding",CHANNEL:"channel",owa:"cta",JIa:"highlightText",NMa:"label",PLAYLIST:"playlist",POPUP:"popup",Uab:"speech",SUBSCRIBE:"subscribe",Jeb:"title",VIDEO:"video",omb:"website"},Grb={H3:"branding",ksa:"card",wya:"drawer",IIa:"highlight",fTa:"marker",Y4a:"promotion",TEXT:"text",Vnb:"widget"};g.y(X3,g.I);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.SI(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.eb.set(a,e);this.context.J.jf([a])};
g.k.oH=function(){this.context.B.subscribe("resize",this.II,this)};
g.k.Ib=function(){return this.element};
g.k.aN=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Hf(this.Ib())};
g.k.II=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=S3(a);if(f){var h=Sqb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Kf||!1,n=g.vA(f||"");m&&n&&(n.v||n.list)?e.context.J.ip(n.v,b,n.list,!1):g.WF(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);i4(this.context.logger,c,l,d);Rqb(f)||(c=g.mE(),d=b.itct,c&&d&&g.GE(c,g.kE(d)))}};
g.k.xa=function(){this.Wa.clear();this.eb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.y(Uqb,X3);g.k=Uqb.prototype;g.k.Ut=function(){this.ra&&b4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Us(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.II=function(){var a=this.isAvailable();g.Vs(this.Ib(),a);g.Rv(this.context.J.getRootNode(),g.xY.IV_DRAWER_ENABLED,a);C3(this.J)};
g.k.destroy=function(){this.J.dC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.uD(this.qa);g.xB(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();X3.prototype.destroy.call(this)};
g.k.RD=function(){var a=this,b=g.tf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.D7,this);this.context.j.listen(this.B,"touchend",function(){a.Fa.start()});
this.context.j.listen(this.B,"scroll",this.Z7,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Mv(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.tD("iv-button-shown",this.u$,this));this.qa.push(g.tD("iv-button-hidden",this.t$,this));arb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Eb(this.cards,function(c){return a.Bf.startMs>c.Bf.startMs||a.Bf.startMs===c.Bf.startMs&&a.Bf.timestamp>=c.Bf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.D7=function(){if(this.C){i4(this.context.logger,f4(this).jj.close);var a=g.mE();a&&this.N&&g.GE(a,this.N);a4(this)}};
g.k.Z7=function(){g.Rv(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.u$=function(){var a=g.mE(),b=f4(this);b=b?b.Hf:this.Hf;a&&b&&g.EE(a,[b])};
g.k.t$=function(){var a=g.mE(),b=f4(this);b=b?b.Hf:this.Hf;a&&b&&g.FE(a,[b])};
g.k.P4=function(){var a=f4(this);i4(this.context.logger,a.jj.l2);var b=g.mE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Pj&&c.push(a.Pj);a.Hf&&c.push(a.Hf);c.length>0&&g.EE(b,c)}else g.EE(b,[a.Pj,a.Hf])};
g.k.v$=function(){var a=g.mE(),b=f4(this);a&&b&&g.FE(a,[b.Pj])};
g.k.O4=function(a){var b=f4(this),c=g.mE();this.j?a?(a=this.context.logger,i4(a,b.jj.uM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Pj&&g.GE(c,b.Pj)):(a=this.context.logger,i4(a,b.jj.uM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hf&&g.GE(c,b.Hf)):(a=this.context.logger,i4(a,b.jj.uM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Hf&&g.GE(c,this.Hf))};g.y(g4,X3);g4.prototype.oH=function(){X3.prototype.oH.call(this);hrb(this)};
g4.prototype.show=function(){X3.prototype.show.call(this);var a=g.mE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.EE(a,[g.kE(b.itct)])};
g4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.mE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.FE(a,[g.kE(b.itct)])};g.y(h4,g4);
h4.prototype.vy=function(){g.Nv(this.Ib(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Vs(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ib().appendChild(b);var c=this.annotation.Ke();c&&Y3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||lrb(this,
a)};
h4.prototype.show=function(){if(!this.isActive&&(g4.prototype.show.call(this),this.N||(this.vy(),this.N=!0),g.Vs(this.Ib(),!0),this.isActive=!0,this.B)){try{irb(this,this.B)}catch(a){}g.Nv(this.context.J.getRootNode(),"ytp-branding-shown")}};
h4.prototype.hide=function(){this.isActive&&(g4.prototype.hide.call(this),g.Vs(this.Ib(),!1),this.isActive=!1,g.Pv(this.context.J.getRootNode(),"ytp-branding-shown"))};
h4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);g4.prototype.destroy.call(this)};g.y(nrb,g4);g.k=nrb.prototype;
g.k.vy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ib().setAttribute("aria-hidden","true");this.Ib().setAttribute("aria-label","Promotion");this.Ib().tabIndex=0;var e=this.annotation.Ke(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Me(f,S3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&Y3(this,
this.Ib(),e,this.annotation.id,b.session_data,void 0,c)}g.Nv(this.j,"iv-click-target");e&&Y3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.Nv(this.j,"iv-click-target"),e&&Y3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){qrb(a,5E3,q)});
c.appendChild(this.B);g.Vs(this.B,!1);this.context.j.listen(this.Ib(),"mouseover",this.s9,this);this.context.j.listen(this.Ib(),"mouseout",this.r9,this);this.context.j.listen(this.Ib(),"touchend",function(q){qrb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.n9:this.m9,this);c.appendChild(this.C);g.Ov(this.Ib(),d);h&&(g.Bf(this.Ib(),h),n&&h.appendChild(n));g.Bf(this.Ib(),this.N);g.Bf(this.Ib(),c)};
g.k.show=function(){this.isActive||(g4.prototype.show.call(this),this.Y||(this.vy(),this.Y=!0),g.Vs(this.Ib(),!0),g.og(function(){g.Pv(this.Ib(),"iv-promo-inactive")},100,this),this.Ib().removeAttribute("aria-hidden"),this.isActive=!0,srb(this),orb(this),prb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Nv(this.Ib(),"iv-promo-inactive"),this.isActive=!1,this.Ib().setAttribute("aria-hidden","true"))};
g.k.aN=function(a,b,c,d,e,f){return this.isCollapsed?!1:g4.prototype.aN.call(this,a,b,c,d,e,f)};
g.k.s9=function(a){this.Z=!0;qrb(this,500,a)};
g.k.r9=function(){this.Z=!1;rrb(this)};
g.k.m9=function(a){a.stopPropagation();this.hide()};
g.k.n9=function(a){a.stopPropagation();srb(this);this.isCollapsed=!0;g.Nv(this.Ib(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();g4.prototype.destroy.call(this)};g.y(urb,g.kV);g.k=urb.prototype;g.k.Th=function(a,b){if(!Jrb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.a2(b))&&zrb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Yqb(this.j,b),C3(this.player)),!0}return null};
g.k.getOptions=function(){return Jrb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Xu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.mT(b)||g.xT(this.player.app)?!1:c===1&&!b.EY||a.Na.get(b.videoId)||g.cT(b)||g.KXa(b)?!0:!1};
g.k.kL=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ts(this.C.element,a.width,a.height);g.Ps(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Wn();a=this.j;b=b.width;g.Rv(a.D,"iv-drawer-small",b<=426);g.Rv(a.D,"iv-drawer-big",b>=1280)}};
g.k.Q4=function(a){wrb(this,a.state);g.BF(a.state,2)&&(this.Vk()&&this.Dp()&&this.player.getPresentingPlayerType()!==2&&this.eC(!1),this.dC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.DA(h)&&h.responseXML?h.responseXML:null)&&(zrb(b,h),g.Nv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.kV.prototype.load.call(this);wrb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.UB()&&(a=Arb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Brb(e,f);f=f&&(f.rO||f.NI);if(!c.Fv||f)c.Va?xrb(this,c.Va,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.bT(h))&&!b.qa&&Frb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.LT(this.player,this.C.element,4);this.kL();(f=g.cT(c))&&Erb(this,f);(f=g.KXa(c))&&f.featuredChannel&&Irb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Zg=g.tf("ytp-cards-button",this.player.getRootNode());g.bT(c)&&Frb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&xrb(this,b.Va,a)};
g.k.unload=function(){this.player.sf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,C3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.kV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.j0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Crb(this):this.load())};
g.k.Vk=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Dp=function(){return!!this.j&&this.j.C};
g.k.eC=function(a,b,c){b=b===void 0?!1:b;this.Vk();this.j&&(a?c?$3(this.j,c,b):$3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.j))};
g.k.dC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.j0,this);g.Pv(this.player.getRootNode(),g.xY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.Cv,c=0,d=a.length;c<d;c++)b.Vj(a[c]);this.ra.length=0;g.kV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.N(this,a);return a.element};g.jV("annotations_module",urb);g.jV("creatorendscreen",qqb);})(_yt_player);
