(function(g){var window=this;'use strict';var gwb=function(a,b){a.ib("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.Rv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.hh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.gS&&(b.lengthText?(e=b.lengthText||null,f=b.vx||null):b.lengthSeconds&&(e=g.LF(b.lengthSeconds),f=g.LF(b.lengthSeconds,!0)));var h=!!d;d=h&&g.bWa(d).type==="RD";var l=b instanceof g.gS?b.isLivePlayback:null,m=b instanceof g.gS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.ZI("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.jl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.gt};b instanceof g.fS&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.U(),c=b.D;
g.W.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ka:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Ka:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},l6=function(a,b){b=b===void 0?!1:b;
g.W.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.W({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Ka:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Ka:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Ka:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.N(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ga("ytp-autonav-endscreen-link-container"),"click",this.NU);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ga("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({I:"div",S:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.W({I:"div",S:"ytp-autonav-endscreen-button-container"});g.N(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.W({I:"button",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.X4,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.W({I:"a",Ka:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.N(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.NU,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&hwb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Gv(function(){iwb(c)},
500);
g.N(this,this.D);this.MU();this.T(a,"autonavvisibility",this.MU);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.W4),this.T(a,"onAutonavCoundownStarted",this.maa))},m6=function(a){var b=a.J.Wn(!0,a.J.isFullscreen());
g.Rv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Qg(b));g.Rv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.pM);g.Rv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.If());g.Rv(a.J.getRootNode(),"countdown-running",a.vl());g.Rv(a.container.element,"ytp-player-content",a.J.If());g.Is(a.overlay.element,{width:b.width+"px"});if(!a.vl()){a.J.If()?jwb(a,Math.round(kwb(a)/1E3)):jwb(a);b=!!a.suggestion&&!!a.suggestion.gt;var c=a.J.If()||!b;
g.Rv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Rv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.QE(a.B,a.J.If());g.Rv(a.element,"ytp-enable-w2w-color-transitions",lwb(a))}},iwb=function(a){var b=kwb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);jwb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.vl()?a.select(!0):a.vl()&&a.D.start()},kwb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.WC;return a===-1||a===void 0?8E3:a}return a.J.Lt()>=0?a.J.Lt():g.mI(a.J.U().experiments,"autoplay_time")||1E4},hwb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.efa;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},lwb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},jwb=function(a,b){b=b===void 0?-1:b;
a=a.j.Ga("ytp-autonav-endscreen-upnext-header");g.Cf(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.zf("Up next in $SECONDS".slice(0,d)));var e=g.yf("span");g.Lv(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Kf(e,b);a.appendChild(e);a.appendChild(g.zf("Up next in $SECONDS".slice(d+c.length)));return}}g.Kf(a,"Up next")},n6=function(a,b){g.W.call(this,{I:"div",
Ka:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.W.call(this,{I:"div",
Ka:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ga("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Gv(this.TI,5E3,this);this.B=0;var b=this.Ga("ytp-upnext-cancel");this.cancelButton=new g.W({I:"button",Ka:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.listen("click",this.Y4,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.N(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ga("ytp-upnext-autoplay-icon");this.T(b,"click",this.Z4);this.api.createClientVe(b,this,115130);this.OU();this.T(a,"autonavvisibility",this.OU);this.T(a,"mdxnowautoplaying",this.Xaa);this.T(a,"mdxautoplaycanceled",this.Yaa);g.Rv(this.element,"ytp-upnext-mobile",this.api.U().B)},mwb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.WC;return a===-1||a===void 0?8E3:a}return a.api.Lt()>=0?a.api.Lt():g.mI(a.api.U().experiments,"autoplay_time")||1E4},nwb=function(a,b){b=mwb(a,b);
var c=Math,d=c.min;var e=(0,g.lC)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.vl()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.vl()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ka:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.W({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l6(this.player);g.N(this,this.B);this.B.Ja(this.element);a.getVideoData().Uf?this.j=this.B:(this.j=new o6(a),g.LT(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.W({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.NJ(this);g.N(this,this.D);g.N(this,this.table);this.table.Ja(this.element);this.table.show();g.N(this,this.N);this.N.Ja(this.table.element);this.hide()},q6=function(a){var b=a.If();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r6=function(a,b){g.W.call(this,{I:"button",
Ka:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.I1();this.buttonType===2&&g.Nv(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.I1);g.QE(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Pe=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r6(a,2);g.N(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},owb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.UV("Subscribe",null,"Unsubscribe",null,!0,!1,b.Nl,b.subscribed,"trailer-endscreen",null,a,!1);g.N(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ga("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},t6=function(a){var b=a.U(),c=g.LJ||g.pR?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",Ka:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Ka:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.NJ(this);g.N(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.NJ(this);g.N(this,this.B);this.K=new g.Gv(function(){g.Nv(b.element,"ytp-show-tiles")},0);
g.N(this,this.K);var c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},V:[g.WE()]});g.N(this,c);c.Ja(this.element);c.listen("click",this.d5,this);this.table=new g.NE({I:"div",S:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ja(this.element);c=new g.W({I:"button",Ka:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},V:[g.XE()]});g.N(this,c);c.Ja(this.element);c.listen("click",this.c5,this);a.getVideoData().Uf?this.j=new l6(a,!0):this.j=
new o6(a);g.N(this,this.j);g.LT(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v6=function(a){return g.MT(a.player)&&a.XD()&&!a.D},w6=function(a){var b=a.If();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.N(this,this.watchButton);this.watchButton.Ja(this.element);g.gkb(a)&&(this.j=new g.c2(a),g.N(this,this.j),this.B=new g.W({I:"div",Ka:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.N(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},swb=function(a){g.kV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.NJ(this);g.N(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.iB(g.zR(c))&&d&&!g.IT(a)?(this.B=!0,this.endScreen=new s6(a,g.zT(a))):a.hd()?this.endScreen=new x6(a):pwb(a)?(this.D=!0,qwb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.Jg?this.endScreen=new owb(a):this.endScreen=new n6(a);g.N(this,this.endScreen);g.LT(a,this.endScreen.element,4);rwb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.TI("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.UI("endscreen"),function(e){b.onCueRangeExit(e)})},qwb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Vl&&a.C===b.Uf)return!1;a.j=b.Vl;a.C=b.Uf;return!0},pwb=function(a){a=a.U();
return a.Dd&&!a.Jg},rwb=function(a){a.player.sf("endscreen");
var b=a.player.getVideoData();b=new g.SI(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.SI(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.jf([b,c])};
g.ET.prototype.Lt=g.ea(15,function(){return this.app.Lt()});
g.C0.prototype.Lt=g.ea(14,function(){return this.getVideoData().WW});
g.AT.prototype.Cs=g.ea(13,function(a){this.Ei().Cs(a)});
g.iW.prototype.Cs=g.ea(12,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.pX.prototype.Cs=g.ea(11,function(a){this.overflowButton&&this.overflowButton.Cs(a)});
g.AT.prototype.Ds=g.ea(10,function(a){this.Ei().Ds(a)});
g.nW.prototype.Ds=g.ea(9,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.pX.prototype.Ds=g.ea(8,function(a){this.shareButton&&this.shareButton.Ds(a)});
g.AT.prototype.hC=g.ea(7,function(a){this.Ei().hC(a)});
g.NV.prototype.hC=g.ea(6,function(a){this.iS!==a&&(this.iS=a,this.Qq())});
g.AT.prototype.gC=g.ea(5,function(a){this.Ei().gC(a)});
g.pX.prototype.gC=g.ea(4,function(a){this.hS!==a&&(this.hS=a,this.Pq())});g.y(k6,g.W);k6.prototype.select=function(){this.J.ip(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.wE||void 0)&&this.J.logClick(this.element)};
k6.prototype.onClick=function(a){g.cU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.y(l6,g.W);g.k=l6.prototype;g.k.ZH=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.jl()),m6(this))};
g.k.vl=function(){return this.C>0};
g.k.qC=function(){this.vl()||(this.C=Date.now(),iwb(this),gwb(this.J,kwb(this)),g.Rv(this.J.getRootNode(),"countdown-running",this.vl()))};
g.k.Zx=function(){this.Kq();iwb(this);var a=this.j.Ga("ytp-autonav-endscreen-upnext-header");a&&g.Kf(a,"Up next")};
g.k.Kq=function(){this.vl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Kq()};
g.k.NU=function(a){g.cU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ga("ytp-autonav-endscreen-link-container")&&(a=this.j.Ga("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.ib("innertubeCommand",this.G),this.Kq()):this.select())};
g.k.X4=function(){this.J.logClick(this.cancelButton.element);g.GT(this.J,!0);this.cancelCommand&&this.J.ib("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&hwb(this,b);var c;this.cancelCommand=(c=b.bfa)==null?void 0:c.command};
g.k.maa=function(a){if(lwb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.TF(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.TF(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.TF(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.TF(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.TF(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.TF(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Rv(this.element,"ytp-w2w-animate",!0)}};
g.k.W4=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.Rv(this.element,"ytp-w2w-animate",!1)};
g.k.MU=function(){var a=this.J.If();this.K&&this.Hb!==a&&g.QE(this,a);m6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ga("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Qg=function(a){return a.width<400||a.height<459};g.y(n6,g.W);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.XD=function(){return!1};
g.k.If=function(){return!1};
g.k.AZ=function(){return!1};g.y(o6,g.W);g.k=o6.prototype;g.k.TI=function(){this.notification&&(this.D.stop(),this.Pc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.ZH=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.OU=function(){g.QE(this,this.api.If());this.api.logVisibility(this.element,this.api.If());this.api.logVisibility(this.Ga("ytp-upnext-autoplay-icon"),this.api.If());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.If())};
g.k.hba=function(){window.focus();this.TI()};
g.k.qC=function(a){var b=this;this.vl()||(g.vD("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.lC)(),this.j=new g.Gv(function(){nwb(b,a)},25),nwb(this,a),gwb(this.api,mwb(this,a)));
g.Pv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.vl=function(){return!!this.j};
g.k.Zx=function(){this.Kq();this.B=(0,g.lC)();nwb(this);g.Nv(this.element,"ytp-upnext-autoplay-paused")};
g.k.Kq=function(){this.vl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.TI(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.hh()}),this.C=this.T(this.notification,"click",this.hba),this.D.start())}this.Kq();this.api.nextVideo(!1,a)};
g.k.Z4=function(a){!g.Jf(this.cancelButton.element,a.target)&&g.cU(a,this.api)&&(this.api.If()&&this.api.logClick(this.Ga("ytp-upnext-autoplay-icon")),this.select())};
g.k.Y4=function(){this.api.If()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.GT(this.api,!0)};
g.k.Xaa=function(a){this.api.getPresentingPlayerType();this.show();this.qC(a)};
g.k.Yaa=function(){this.api.getPresentingPlayerType();this.Kq();this.hide()};
g.k.xa=function(){this.Kq();this.TI();g.W.prototype.xa.call(this)};g.y(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.D.T(this.player,"appresize",this.fD);this.D.T(this.player,"onVideoAreaChange",this.fD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.PU);this.D.T(this.player,"onAutonavCancelled",this.a5);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.GT(this.player,!1);g.MT(this.player)&&this.XD()&&!this.C?(q6(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.qC():this.videoData.autonavState===3&&this.j.Zx()):(g.GT(this.player,!0),q6(this));this.fD()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.Zx();q6(this)};
g.k.fD=function(){var a=this.player.Wn(!0,this.player.isFullscreen());q6(this);m6(this.B);g.Rv(this.element,"ytp-autonav-cancelled-small-mode",this.Qg(a));g.Rv(this.element,"ytp-autonav-cancelled-tiny-mode",this.sK(a));g.Rv(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.Is(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Rv(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.HS(this.videoData);b&&(this.j.ZH(b),this.j!==this.B&&this.B.ZH(b))}if(a&&a.length)for(b=0;b<twb.length;++b){var c=twb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.N(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.fD()}};
g.k.PU=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Kq(),this.Hb&&this.fD()):(this.K=!0,this.If()&&(a===2?this.j.qC():a===3&&this.j.Zx()))};
g.k.a5=function(a){a?this.PU(1):(this.C=null,this.K=!1)};
g.k.XD=function(){return this.videoData.autonavState!==1};
g.k.Qg=function(a){return(a.width<910||a.height<459)&&!this.sK(a)&&!(a.width<=400||a.height<=360)};
g.k.sK=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.If=function(){return this.Hb&&g.MT(this.player)&&this.XD()&&!this.C};
var twb=[1,3,2,4];g.y(r6,g.W);g.k=r6.prototype;g.k.I1=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.dU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.qR(b)){var c={};g.qR(b)&&g.tT(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.MO(c,b);a=g.to(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Hb&&this.Z)};
g.k.show=function(){g.W.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.logVisibility()};
g.k.Mc=function(a){g.W.prototype.Mc.call(this,a);this.logVisibility()};g.y(s6,n6);s6.prototype.show=function(){this.player.getPlayerState()!==3&&(n6.prototype.show.call(this),this.Pe.gC(!0),this.Pe.Ds(!0),this.J.U().Ge||this.Pe.Cs(!0),this.J.logVisibility(this.element,!0),this.watchButton.Mc(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.Pe.gC(!1);this.Pe.Ds(!1);this.Pe.Cs(!1);this.J.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.y(owb,n6);owb.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Nl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.y(t6,g.W);t6.prototype.select=function(){this.api.ip(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.wE||void 0)&&this.api.logClick(this.element)};
t6.prototype.onClick=function(a){if(g.qR(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.jl(),c={};g.CYa(this.api,c,"emb_rel_end");b=g.to(b,c);g.dU(b,this.api,a)}else g.cU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Kf?!1:b.D};g.y(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Wq();this.B.T(this.player,"appresize",this.Wq);this.B.T(this.player,"onVideoAreaChange",this.Wq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.dN);this.B.T(this.player,"onAutonavCancelled",this.b5);a=this.videoData.autonavState;a!==this.Y&&this.dN(a);this.B.T(this.element,"transitionend",this.vca)};
g.k.destroy=function(){g.xB(this.B);g.wb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.Pv(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.XD=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Hb;n6.prototype.show.call(this);g.Pv(this.element,"ytp-show-tiles");this.player.U().B?g.Iv(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.GT(this.player,!1);v6(this)?(w6(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.qC():this.videoData.autonavState===3&&this.j.Zx()):(g.GT(this.player,!0),w6(this));a!==this.Hb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Hb;n6.prototype.hide.call(this);this.j.Zx();w6(this);a!==this.Hb&&this.player.logVisibility(this.element,!1)};
g.k.vca=function(a){a.target===this.element&&this.Wq()};
g.k.Wq=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.HS(d)];if(e.length){g.Nv(this.element,"ytp-endscreen-paginate");var f=this.J.Wn(!0,this.J.isFullscreen());if(a=g.zT(this.J))a=a.Hh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Ts(f,n,p);g.Is(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.ZH(g.HS(this.videoData));this.j instanceof
l6&&m6(this.j);g.Rv(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Ae(q+this.C,c),t!==0){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var w=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-u-4,C=Math.floor(n*(l+t)/a)-w-4;g.Ps(r.element,w,u);g.Ts(r.element,C,A);g.Is(r.element,"transitionDelay",
(m+l)/20+"s");g.Rv(r.element,"ytp-videowall-still-mini",t===1);g.Rv(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,A);g.Rv(r.element,"ytp-videowall-still-round-large",t>=256);g.Rv(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.Rv(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.Mv(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,u),g.qR(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.jl(),u={},g.tT(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.to(t,g.MO(u,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.Rv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Hf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.HS(a)?(this.C=0,this.videoData=a,this.Wq()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.c5=function(){this.C+=this.stills.length;this.Wq()};
g.k.d5=function(){this.C-=this.stills.length;this.Wq()};
g.k.AZ=function(){return this.j.vl()};
g.k.dN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Kq(),this.Hb&&this.Wq()):(this.G=!0,this.Hb&&v6(this)&&(a===2?this.j.qC():a===3&&this.j.Zx()))};
g.k.b5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.dN(1)}else this.D=null,this.G=!1;this.Wq()};
g.k.If=function(){return this.Hb&&v6(this)};g.y(x6,n6);x6.prototype.show=function(){if(this.player.getPlayerState()!==3){n6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.Rv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.zT(this.player))==null||c.hC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Mc(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;(a=g.zT(this.player))==null||a.hC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.y(swb,g.kV);g.k=swb.prototype;g.k.Xu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.hd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.HS(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!pwb(this.player)||d;a=a.Hj;c=this.player.IE();return d&&!a&&!c&&!b};
g.k.If=function(){return this.endScreen.If()};
g.k.Y9=function(){return this.If()?this.endScreen.AZ():!1};
g.k.xa=function(){this.player.sf("endscreen");g.kV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.zb().Fe.get("heartbeat"),d=g.HS(a);!d||b.videoId!==d.videoId||a.VV?(this.player.ip(b.videoId,void 0,void 0,!0,!0,b),c&&c.CK("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.kV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.kV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Xu()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){rwb(this);this.D&&qwb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.N(this,this.endScreen),g.LT(this.player,this.endScreen.element,4))};g.jV("endscreen",swb);})(_yt_player);
